### ISSUE TITLE
Example sender isn't looping as suggested in README

### ISSUE THREAD

**Issue by setherith** [open-dis/open-dis-python#30]
The README.md suggests that after running the dis_sender.py the user should press Ctrl + \ to stop the process. But when I run the script it sends a single Entity State PDU and stops. The code in the dis_sender.py supports this and doesn't contain a loop.

**Comment by leif81** [comment]
Thanks for the report @setherith 

Can I interest you in submitting a pull request with the correction?

**Comment by setherith** [comment]
Certainly! How would you like it? I can add the missing loop and escape function or I can update the document to remove the statement about the loop? Happy to do both :)

**Comment by leif81** [comment]
Lets add the loop that re-sends the same position, say every 60 seconds. Plus the escape function. 

Then the example becomes a bit more useful, in the sense it could be started and left running. Giving time to watch the entity appear in another simulation, rather than the entity timing out after one heartbeat.
