### ISSUE TITLE
Will this become a Pip package?

### ISSUE THREAD

**Issue by ztolley** [open-dis/open-dis-python#44]
Are there any plans to make this a package installable via pip with versioned releases to help reliant projects pickup new fixes?

**Comment by leif81** [comment]
@ztolley yes that was my intent. I tried a while back and hit a snag, maybe it's time I retry.

**Comment by ngjunsiang** [comment]
Could I check what is the oldest version of Python 3 this package would be intended to support?

**Comment by leif81** [comment]
@ngjunsiang i'm not sure how to determine that

**Comment by ngjunsiang** [comment]
I am asking primarily because this would determine the main style and syntax to be used (e.g. `class DataQueryDatumSpecification( object ):` is required by Python2, but Python3 only requires `class DataQueryDatumSpecification:`)

Secondarily, Python3 versions 3.7 and up add new syntax features that might not be supported in earlier versions. E.g. [dataclasses](https://docs.python.org/3/library/dataclasses.html) are only available for version 3.7, and would need an external import for support in 3.6 and earlier.

I noted that the README states this is a Python 3 implementation of DIS 7, so I assume this is not meant to be backward-compatible with any Python version earlier than 3.0. I am trying to determine which newer Python features I can use if I want to make any pull requests.

Furthermore, if packaging work is to be done, the Python requirement needs to be stated in `pyproject.toml` (with reference to the [Python Packaging User Guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/)). I can help with this work when my commitments free up somewhat in the second half of this year. But I don't know how to begin finding out where open-dis-python is already being adopted, so as to avoid breaking backward compatibility with those projects if they switch to a pip-based install instead of building from source.

**Comment by ngjunsiang** [comment]
Assuming there is no major prior use of open-dis-python that needs backward compatibility to be supported, I would recommend the following minimum versions:

### Python 3.5

This is the earliest version that supports type annotations in functions and methods. This would make the code more readable and easier to understand at a glance, especially for those used to type specifications from Java and C++

#### Annotated functions, before and after
![image](https://github.com/open-dis/open-dis-python/assets/45561895/6e4f14a4-2942-438e-a229-93913d7f2004)
![image](https://github.com/open-dis/open-dis-python/assets/45561895/f8f0ce42-c929-4a50-b68a-7b905b46ef53)

### Python 3.7

This is the earliest version that introduces dataclasses and the `dataclass` decorator and `field` object. The `dataclass` decorator uses type annotations on class attributes and uses them to provide default `__init__()` and `__repr__()` behaviour, which make introspection much easier with less code.

#### Before dataclass
![image](https://github.com/open-dis/open-dis-python/assets/45561895/fc802654-bf32-40fe-8b42-c8d741327629)
![image](https://github.com/open-dis/open-dis-python/assets/45561895/c5e9546d-9ea3-46dc-8105-8c19d5650a72)

#### After dataclass (with type annotations)
![image](https://github.com/open-dis/open-dis-python/assets/45561895/62e5bf64-19ed-4a32-ae50-0c325dadee91)
![image](https://github.com/open-dis/open-dis-python/assets/45561895/447c0805-3f29-4cde-bd4a-da18b8ff8aa5)

**Comment by leif81** [comment]
@ngjunsiang It's difficult to know what version of Python users of the library are using.

I see that Python 3.5 was released in 2015 and Python 3.7 in 2018. And based on [W3 stats for Python 3](https://w3techs.com/technologies/history_details/pl-python/3) (I'm not sure if these are the best stats) I see the following use in the Python 3 community:
- 1.2% of users are using a version older than 3.5.
- 33.8% of users are using a version older than 3.7.

Based on those stats, we may alienate up to 1/3 of the users by upgrading to 3.7 today, whereas almost no one would be impacted by updating to 3.5. On this info alone, I would suggest setting the base version to 3.5.

Two questions for the open-dis-python community. Lets leave this question open for a week to collect feedback.
1. Are you using a version of Python older than 3.5?
2. Would you be able to upgrade your application to Python 3.5?

**Comment by scottrbrtsn** [comment]
Maybe consider a `pyproject.toml`? 
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

for enabling poetry-like integrations:  https://python-poetry.org/docs/pyproject/

**Comment by scottrbrtsn** [comment]
This issue would make installing to Dockerfiles much easier also.  I'm wondering if a docker swarm/k8s example would be worth the effort?

**Comment by scottrbrtsn-ata-llc** [comment]
fysa, this `open-dis-python` requires numpy, which appears to need python 3.9

https://github.com/open-dis/open-dis-python/pull/50#issuecomment-1972350387

**Comment by scottrbrtsn** [comment]
fysa it appears that `open-dis-python` requires python 3.9 per: https://github.com/open-dis/open-dis-python/pull/50#issuecomment-1972350387

**Comment by leif81** [comment]
@scottrbrtsn good catch. If we're already dependent on 3.9+ then we might as well stay with that baseline version.

**Comment by scottrbrtsn** [comment]
Didn't think of this option:  
`pip install git+https://github.com/open-dis/open-dis-python` works as is until a package is created in the global pypi.
